[package]
name = "uhpo"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bitcoin = {version = "0.32.2" , features = ["rand"] }
rand = "0.8.5"
bitcoincore-rpc = "0.19.0"
hex = "0.4.3"